name: Exploring
favicon: null
layout_spectrum: 0.62568
typography_spectrum: 0.25811
title: Exploring
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-66287116-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#333333'
    - '#ffffff'
    - '#636363'
    - '#cfcfcf'
    - '#000000'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose:
  - name: engagement
    item: a2b71f00-6a95-4e98-a68f-70e73393a27e
    url: 'http://mrmrs.cc'
